# Generated by Django 4.2.2 on 2023-06-27 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('students', 'UserProfile')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
