# Generated by Django 4.2.2 on 2023-07-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
